services:
###########################################################################
### Default configuration for this services
### TODO: Should be changed
###########################################################################
    _defaults:
        autowire: true
        autoconfigure: false
        public: true

###########################################################################
### App Forms
###########################################################################
    app.form.registration:
            class: AppBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }

    app.form.user:
            class: AppBundle\Form\UserType
            tags:
                - { name: form.type, alias: app_user_form }

###########################################################################
### Controllers
###########################################################################
    app.controller.user:
        class: AppBundle\Controller\UserController
        arguments: ['@security.user_password_encoder.generic']

###########################################################################
### App Listeners
###########################################################################
    app.registration_listener:
        class: AppBundle\EventListener\UserRegistrationListener
        arguments: ['@router']
        tags:
            - { name: kernel.event_subscriber }

###########################################################################
### Other
###########################################################################
    app.twig.app_extension:
        class: AppBundle\Twig\AppExtension
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: twig.extension }